### ISSUE TITLE
Edit Project Description: Due Sept 23 2022

### ISSUE THREAD

**Issue by SammyRobensParadise** [FYDPE/docs#35]
## Description
This task is tracking the editing process for the different sections of the project description. When we think a section is 👨‍🍳+ 💋 we can check it off

## Subtasks
Check off the following when the editing is complete

- [x] Introduction
- [x] Situation of Concern
- [x] Problem Focus
- [x] Needs Assessment and Prior Art
- [x] Ethical Implications of Project
- [x] Project Objectives and Outcomes
- [x] Systems Design Engineering Approach
- [x] Resource Management
- [x] References

## Depends on

- #23 
- #24 
- #25 
- #26
- #27 
- #28 
- #29 
- #30 
- #31 

## Is this task part of a graded deliverable?
Yes

## Requirements to close task/issue
Complete the above tasks

## References and Links
[doc](https://docs.google.com/document/d/1GsL7NcwMCmw3_-SbSwZfy56D_MA66UNeyB6AIqSaKBE/edit#heading=h.bfp7dikg11cz)

**Comment by SammyRobensParadise** [comment]
the first round of edits completed on
- Introduction
- Situation of Concern
- Problem Focus

**Comment by hnagri52** [comment]
Completed edits on:
- Needs Assessment and Prior Art

**Comment by SammyRobensParadise** [comment]
Secondary review on 
- Needs Assessment and Prior Art!

**Comment by SammyRobensParadise** [comment]
closing as done since we are submitting 
<img width="253" alt="Screen Shot 2022-09-22 at 11 15 52 PM" src="https://user-images.githubusercontent.com/33642354/191885855-30498684-b4f4-494d-9ddd-e32b7df0b0c6.png">
